"""
Tests for :mod:`acidbase.security.patcher`.

The shell layer is replaced with a recording fake so the test asserts on the
exact sequence of git/uv invocations used by the patch flow.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

from acidbase.security import patcher
from acidbase.security.patcher import PatchResult, PatchStatus, patch_repo
from acidbase.security.profiles import Profile
from acidbase.security.shell import CommandResult

_UV_LOCK = 'version = 1\n\n[[package]]\nname = "{dep}"\nversion = "{ver}"\n'
_UV_EXPORT_HEADER = (
    "# This file was autogenerated by uv via the following command:\n"
    "#    uv export --no-hashes --no-dev -o producer/requirements.txt\n"
)
_ROOT_EXPORT_HEADER = (
    "# This file was autogenerated by uv via the following command:\n"
    "#    uv export --frozen --output-file=requirements.txt\n"
)


class RecordingShell:
    """Fake replacement for :func:`acidbase.security.shell.run` used in tests."""

    def __init__(self, responses: dict[tuple[str, ...], CommandResult]) -> None:
        self.responses = responses
        self.calls: list[tuple[str, ...]] = []

    def __call__(
        self,
        args,
        *,
        cwd: Optional[Path] = None,
        capture: bool = True,
        check: bool = False,
        env=None,
    ) -> CommandResult:
        key = tuple(args)
        self.calls.append(key)
        for pattern, result in self.responses.items():
            if all(seg in key for seg in pattern):
                return result
        return CommandResult(returncode=0, stdout="", stderr="")


def _make_repo(tmp_path: Path, *, with_requirements: bool = False) -> Path:
    """Creates a fake repo skeleton (uv.lock + optionally requirements.txt)."""
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "uv.lock").write_text("# fake lock\n", encoding="utf-8")
    (repo / "pyproject.toml").write_text("[project]\nname='r'\nversion='0'\n", encoding="utf-8")
    if with_requirements:
        (repo / "requirements.txt").write_text("", encoding="utf-8")
    return repo


def test_patch_repo_returns_missing_when_path_absent(tmp_path, monkeypatch):
    """Returns MISSING without invoking shell when the local clone does not exist."""
    monkeypatch.setattr(patcher, "shell", _stub_module(RecordingShell({})))
    profile = Profile(repo="x", path=tmp_path / "nope")
    result = patch_repo(profile, dep_name="GitPython", new_version="3.1.50", cve_id="CVE-1")
    assert result.status is PatchStatus.MISSING


def test_patch_repo_returns_dirty_when_working_tree_unclean(tmp_path, monkeypatch):
    """Returns DIRTY when ``git status --porcelain`` reports changes."""
    repo = _make_repo(tmp_path)
    fake = RecordingShell(
        {
            ("git", "--no-pager", "status", "--porcelain", "--untracked-files=no"): CommandResult(0, " M file\n", ""),
        }
    )
    monkeypatch.setattr(patcher, "shell", _stub_module(fake))
    profile = Profile(repo="r", path=repo)
    result = patch_repo(profile, dep_name="GitPython", new_version="3.1.50", cve_id="CVE-1")
    assert result.status is PatchStatus.DIRTY
    assert result.note == "uncommitted changes"


def test_patch_repo_returns_giterror_when_git_status_fails(tmp_path, monkeypatch):
    """Returns GITERROR (not DIRTY) when `git status` exits non-zero.

    Regression test for the WSL UNC misdiagnosis: prior to the
    ``_check_clean`` refactor, every non-zero exit from ``git status``
    (e.g. the ``fatal: detected dubious ownership in repository at '...'``
    that hits when Windows-native git runs against a WSL share) was
    collapsed into ``DIRTY`` / ``uncommitted changes``. The new behavior
    is to surface the real stderr through a dedicated ``GITERROR`` status.
    """
    repo = _make_repo(tmp_path)
    fake = RecordingShell(
        {
            ("git", "--no-pager", "status", "--porcelain", "--untracked-files=no"): CommandResult(
                128,
                "",
                "fatal: detected dubious ownership in repository at '//wsl.localhost/Ubuntu/home/user/some-repo'\n",
            ),
        }
    )
    monkeypatch.setattr(patcher, "shell", _stub_module(fake))
    profile = Profile(repo="r", path=repo)
    result = patch_repo(profile, dep_name="GitPython", new_version="3.1.50", cve_id="CVE-1")
    assert result.status is PatchStatus.GITERROR
    assert "dubious ownership" in result.note
    # The 200-char stderr truncation means the full URL may be cut, but the
    # diagnostic keyword has to be present.


def test_patch_repo_returns_selfskip_when_targeting_own_project_on_windows(tmp_path, monkeypatch):
    """Returns SELFSKIP with a copy-pasteable command when acidbase is asked to patch itself on Windows.

    Regression test for the python-dotenv UVADDFAIL on acidbase: the running
    python.exe holds open handles on its own site-packages files (rich →
    pygments, python-dotenv, click, ...), so an inner `uv add` against the
    same venv fails on Windows with `error: failed to remove file '...'`.
    The new SELFSKIP status defers the bump and surfaces a manual command
    instead of misreporting it as UVADDFAIL.
    """
    repo = _make_repo(tmp_path)
    monkeypatch.setattr(patcher, "shell", _stub_module(RecordingShell({})))
    monkeypatch.setattr(patcher, "_is_self_patching", lambda p: True)
    monkeypatch.setattr(patcher.sys, "platform", "win32")
    profile = Profile(repo="acidbase", path=repo, branch="main")
    result = patch_repo(profile, dep_name="Pygments", new_version="2.20.0", cve_id="CVE-1")
    assert result.status is PatchStatus.SELFSKIP
    # The user-facing note contains a runnable command sequence.
    assert "uv add" in result.note
    assert "Pygments>=2.20.0" in result.note
    assert "git push" in result.note


def test_patch_repo_proceeds_normally_when_self_patching_on_posix(tmp_path, monkeypatch):
    """SELFSKIP only fires on Windows; POSIX unlink-while-open semantics let uv proceed."""
    repo = _make_repo(tmp_path, with_requirements=True)
    calls: list[tuple[str, ...]] = []
    state = {"status_calls": 0}

    def fake_run(args, *, cwd=None, capture=True, check=False, env=None):
        key = tuple(args)
        calls.append(key)
        if key == ("git", "--no-pager", "status", "--porcelain", "--untracked-files=no"):
            state["status_calls"] += 1
            if state["status_calls"] == 1:
                return CommandResult(0, "", "")
            return CommandResult(0, "M pyproject.toml\n", "")
        return CommandResult(0, "", "")

    monkeypatch.setattr(patcher, "shell", _stub_module(fake_run))
    monkeypatch.setattr(patcher, "_is_self_patching", lambda p: True)
    monkeypatch.setattr(patcher.sys, "platform", "linux")
    profile = Profile(repo="acidbase", path=repo, branch="main")
    result = patch_repo(profile, dep_name="Pygments", new_version="2.20.0", cve_id="CVE-1")
    # Reaches DONE without ever taking the SELFSKIP branch.
    assert result.status is PatchStatus.DONE
    assert ("uv", "add", "--no-sync", "Pygments>=2.20.0") in calls


def test_is_self_patching_returns_false_for_unrelated_path(tmp_path):
    """_is_self_patching is conservative: arbitrary paths never count as self-patching."""
    assert patcher._is_self_patching(tmp_path / "some-other-repo") is False


def test_is_self_patching_returns_true_for_own_project_root():
    """_is_self_patching matches the acidbase project root the test itself runs from."""
    own_root = patcher._own_project_root()
    assert own_root is not None
    assert patcher._is_self_patching(own_root) is True


def test_self_skip_command_includes_requirements_export_when_file_exists(tmp_path):
    """The self-skip command suggests `uv export` only for a uv-export-artifact root file."""
    # _make_repo() expects its parent to exist already, so create the three
    # sibling parent dirs first before delegating.
    (tmp_path / "with").mkdir()
    (tmp_path / "without").mkdir()
    (tmp_path / "curated").mkdir()
    repo_with = _make_repo(tmp_path / "with", with_requirements=True)
    (repo_with / "requirements.txt").write_text(_ROOT_EXPORT_HEADER + "pytest==9.0.2\n", encoding="utf-8")
    cmd_with = patcher._self_skip_command(repo_with, "pytest", "9.0.3", "CVE-X")
    assert "uv export --frozen --output-file=requirements.txt" in cmd_with
    assert "requirements.txt" in cmd_with

    repo_without = _make_repo(tmp_path / "without")
    cmd_without = patcher._self_skip_command(repo_without, "pytest", "9.0.3", "CVE-X")
    assert "uv export" not in cmd_without
    assert "requirements.txt" not in cmd_without

    # A curated root file (no uv-export header) must not be suggested for export either.
    repo_curated = _make_repo(tmp_path / "curated", with_requirements=True)
    (repo_curated / "requirements.txt").write_text(
        "# synced by scripts/sync_requirements.py\npytest\n", encoding="utf-8"
    )
    cmd_curated = patcher._self_skip_command(repo_curated, "pytest", "9.0.3", "CVE-X")
    assert "uv export" not in cmd_curated
    assert "git add pyproject.toml uv.lock" in cmd_curated


def test_check_clean_distinguishes_clean_dirty_and_errored(tmp_path, monkeypatch):
    """_check_clean returns the documented 3-state tuple for each outcome."""
    repo = _make_repo(tmp_path)
    # Clean: rc=0, empty stdout
    fake_clean = RecordingShell({("git", "--no-pager", "status"): CommandResult(0, "", "")})
    monkeypatch.setattr(patcher, "shell", _stub_module(fake_clean))
    assert patcher._check_clean(repo) == (True, None)

    # Dirty: rc=0, non-empty stdout
    fake_dirty = RecordingShell({("git", "--no-pager", "status"): CommandResult(0, " M pyproject.toml\n", "")})
    monkeypatch.setattr(patcher, "shell", _stub_module(fake_dirty))
    assert patcher._check_clean(repo) == (False, None)

    # Errored: rc != 0 — error message is surfaced (truncated to 200 chars)
    fake_err = RecordingShell({("git", "--no-pager", "status"): CommandResult(128, "", "fatal: dubious ownership\n")})
    monkeypatch.setattr(patcher, "shell", _stub_module(fake_err))
    clean, err = patcher._check_clean(repo)
    assert clean is False
    assert err is not None
    assert "dubious ownership" in err


def test_patch_repo_returns_notuv_when_lock_missing(tmp_path, monkeypatch):
    """Returns NOTUV when ``uv.lock`` is absent even on a clean tree."""
    repo = tmp_path / "repo"
    repo.mkdir()
    fake = RecordingShell({})
    monkeypatch.setattr(patcher, "shell", _stub_module(fake))
    profile = Profile(repo="r", path=repo)
    result = patch_repo(profile, dep_name="GitPython", new_version="3.1.50", cve_id="CVE-1")
    assert result.status is PatchStatus.NOTUV


def test_patch_repo_dry_run_skips_side_effects(tmp_path, monkeypatch):
    """Dry-run returns WOULD-RUN without ever invoking uv/git mutators."""
    repo = _make_repo(tmp_path)
    fake = RecordingShell({})
    monkeypatch.setattr(patcher, "shell", _stub_module(fake))
    profile = Profile(repo="r", path=repo, branch="main")
    result = patch_repo(
        profile,
        dep_name="GitPython",
        new_version="3.1.50",
        cve_id="CVE-1",
        dry_run=True,
    )
    assert result.status is PatchStatus.WOULD_RUN
    assert ("uv", "add") not in {tuple(c[:2]) for c in fake.calls}


def test_patch_repo_full_happy_path(tmp_path, monkeypatch):
    """Clean tree + uv.lock produces DONE with the expected commit invocation."""
    repo = _make_repo(tmp_path, with_requirements=True)
    state = {"status_calls": 0}
    calls: list[tuple[str, ...]] = []

    def fake_run(args, *, cwd=None, capture=True, check=False, env=None):
        key = tuple(args)
        calls.append(key)
        if key == ("git", "--no-pager", "status", "--porcelain", "--untracked-files=no"):
            state["status_calls"] += 1
            # First status call (pre-flight) is clean; second (post-bump) is dirty.
            if state["status_calls"] == 1:
                return CommandResult(0, "", "")
            return CommandResult(0, "M pyproject.toml\n", "")
        return CommandResult(0, "", "")

    monkeypatch.setattr(patcher, "shell", _stub_module(fake_run))
    profile = Profile(repo="r", path=repo, branch="main")
    result = patch_repo(profile, dep_name="GitPython", new_version="3.1.50", cve_id="CVE-1")
    assert result.status is PatchStatus.DONE
    assert result.note == "bumped to >=3.1.50"
    # The bump invocation must use the >=NEW form expected by the runbook,
    # and --no-sync so the target repo's venv is never touched.
    assert ("uv", "add", "--no-sync", "GitPython>=3.1.50") in calls
    # Commit message follows the runbook template verbatim.
    assert any(
        c[:3] == ("git", "commit", "-m") and "security: update GitPython to 3.1.50 to fix CVE-1" in c for c in calls
    )
    # --sync-env is opt-in: no environment sync happens by default.
    assert not any(c[:2] == ("uv", "sync") for c in calls)


def _stub_module(fake_run):
    """Returns a tiny stand-in module exposing only the symbols patcher needs."""

    class Stub:
        run = fake_run
        # Defaulting to "not a WSL mount"; sync-gate tests override per case.
        wsl_routing = staticmethod(lambda cwd: None)
        CommandResult = CommandResult  # noqa: N815 (mirroring real module)

    return Stub


def _make_npm_repo(
    tmp_path: Path,
    *,
    lockfile_contents: dict,
    package_json_contents: Optional[dict] = None,
    subdir: str = ".",
    extra_files: tuple[str, ...] = (),
) -> Path:
    """Creates a fake npm repo skeleton with a package-lock.json (and optional siblings)."""
    repo = tmp_path / "repo"
    repo.mkdir()
    target = repo if subdir == "." else repo / subdir
    target.mkdir(parents=True, exist_ok=True)
    (target / "package-lock.json").write_text(json.dumps(lockfile_contents), encoding="utf-8")
    if package_json_contents is not None:
        (target / "package.json").write_text(json.dumps(package_json_contents), encoding="utf-8")
    for filename in extra_files:
        (target / filename).write_text("", encoding="utf-8")
    return repo


def test_discover_npm_dir_returns_root_when_lockfile_at_root(tmp_path):
    """`_discover_npm_dir` returns '.' for repos with a top-level package-lock.json."""
    (tmp_path / "package-lock.json").write_text("{}", encoding="utf-8")
    assert patcher._discover_npm_dir(tmp_path) == "."


def test_discover_npm_dir_returns_subdir_when_unique(tmp_path):
    """A unique nested package-lock.json (e.g. frontend/) is auto-discovered."""
    sub = tmp_path / "frontend"
    sub.mkdir()
    (sub / "package-lock.json").write_text("{}", encoding="utf-8")
    assert patcher._discover_npm_dir(tmp_path) == "frontend"


def test_discover_npm_dir_returns_none_on_ambiguity(tmp_path):
    """Two candidate npm projects make discovery refuse to guess."""
    for name in ("frontend", "admin"):
        (tmp_path / name).mkdir()
        (tmp_path / name / "package-lock.json").write_text("{}", encoding="utf-8")
    assert patcher._discover_npm_dir(tmp_path) is None


def test_discover_npm_dir_ignores_node_modules(tmp_path):
    """Lockfiles nested under node_modules do not count as the project's own."""
    real = tmp_path / "frontend"
    real.mkdir()
    (real / "package-lock.json").write_text("{}", encoding="utf-8")
    nm = tmp_path / "frontend" / "node_modules" / "foo"
    nm.mkdir(parents=True)
    (nm / "package-lock.json").write_text("{}", encoding="utf-8")
    assert patcher._discover_npm_dir(tmp_path) == "frontend"


def test_detect_unsupported_lockfile_flags_pnpm_yarn_bun(tmp_path):
    """yarn.lock / pnpm-lock.yaml / bun.lockb each produce a human-readable note."""
    for filename in ("pnpm-lock.yaml", "yarn.lock", "bun.lockb"):
        sub = tmp_path / filename.replace(".", "_")
        sub.mkdir()
        (sub / filename).write_text("", encoding="utf-8")
        note = patcher._detect_unsupported_lockfile(sub)
        assert note is not None and filename in note


def test_read_npm_lock_version_handles_v3_packages_key(tmp_path):
    """v2/v3 lockfile (top-level `packages` map) is parsed for the bare package name."""
    lock = tmp_path / "package-lock.json"
    lock.write_text(
        json.dumps(
            {
                "lockfileVersion": 3,
                "packages": {
                    "": {"name": "app", "version": "1.0.0"},
                    "node_modules/yaml": {"version": "2.8.1"},
                },
            }
        ),
        encoding="utf-8",
    )
    assert patcher._read_npm_lock_version(lock, "yaml") == "2.8.1"


def test_read_npm_lock_version_handles_v1_dependencies(tmp_path):
    """npm v1 lockfile (`dependencies` map keyed by name) is parsed correctly."""
    lock = tmp_path / "package-lock.json"
    lock.write_text(
        json.dumps(
            {
                "lockfileVersion": 1,
                "dependencies": {"yaml": {"version": "2.8.0"}},
            }
        ),
        encoding="utf-8",
    )
    assert patcher._read_npm_lock_version(lock, "yaml") == "2.8.0"


def test_read_npm_lock_version_handles_scoped_packages(tmp_path):
    """Scoped names like `@types/node` resolve through the `node_modules/@scope/pkg` key."""
    lock = tmp_path / "package-lock.json"
    lock.write_text(
        json.dumps(
            {
                "lockfileVersion": 3,
                "packages": {
                    "node_modules/@types/node": {"version": "22.0.0"},
                },
            }
        ),
        encoding="utf-8",
    )
    assert patcher._read_npm_lock_version(lock, "@types/node") == "22.0.0"


def test_ensure_npm_override_inserts_new_entry(tmp_path):
    """`_ensure_npm_override` adds the dep to a missing `overrides` block."""
    pkg = tmp_path / "package.json"
    pkg.write_text(json.dumps({"name": "app", "version": "1.0.0"}), encoding="utf-8")
    wrote = patcher._ensure_npm_override(pkg, "yaml", "2.8.3")
    assert wrote is True
    data = json.loads(pkg.read_text(encoding="utf-8"))
    assert data["overrides"] == {"yaml": "^2.8.3"}


def test_ensure_npm_override_is_idempotent_when_same_pin(tmp_path):
    """Calling override with the same floor twice does not rewrite the file."""
    pkg = tmp_path / "package.json"
    pkg.write_text(
        json.dumps({"name": "app", "overrides": {"yaml": "^2.8.3"}}),
        encoding="utf-8",
    )
    assert patcher._ensure_npm_override(pkg, "yaml", "2.8.3") is False


def test_patch_repo_npm_returns_notnpm_when_no_lockfile(tmp_path, monkeypatch):
    """`ecosystem="npm"` against a non-npm repo yields NOTNPM with a helpful note."""
    repo = tmp_path / "repo"
    repo.mkdir()
    monkeypatch.setattr(patcher, "shell", _stub_module(RecordingShell({})))
    profile = Profile(repo="r", path=repo)
    result = patch_repo(
        profile,
        dep_name="yaml",
        new_version="2.8.3",
        cve_id="CVE-1",
        ecosystem="npm",
    )
    assert result.status is PatchStatus.NOTNPM


def test_patch_repo_npm_returns_unsupported_when_yarn_lock_present(tmp_path, monkeypatch):
    """yarn.lock alongside no package-lock.json yields UNSUPPORTED_LOCKFILE."""
    repo = _make_npm_repo(tmp_path, lockfile_contents={}, extra_files=("yarn.lock",))
    # _make_npm_repo wrote both files; remove the helpful package-lock.json so we hit yarn first.
    (repo / "package-lock.json").unlink()
    # _discover_npm_dir requires a lockfile somewhere; without one we get NOTNPM instead of
    # UNSUPPORTED_LOCKFILE. Simulate the realistic case: yarn-only project, npm_dir set explicitly.
    monkeypatch.setattr(patcher, "shell", _stub_module(RecordingShell({})))
    profile = Profile(repo="r", path=repo, npm_dir=".")
    result = patch_repo(
        profile,
        dep_name="yaml",
        new_version="2.8.3",
        cve_id="CVE-1",
        ecosystem="npm",
    )
    assert result.status is PatchStatus.UNSUPPORTED_LOCKFILE
    assert "yarn" in result.note


def test_patch_repo_npm_noop_when_lockfile_already_at_target(tmp_path, monkeypatch):
    """If `package-lock.json` already pins >= new_version, return NOOP without npm install."""
    repo = _make_npm_repo(
        tmp_path,
        lockfile_contents={
            "lockfileVersion": 3,
            "packages": {"node_modules/yaml": {"version": "2.8.5"}},
        },
        package_json_contents={"name": "app"},
    )
    calls: list[tuple[str, ...]] = []

    def fake_run(args, **_kw):
        key = tuple(args)
        calls.append(key)
        return CommandResult(0, "", "")

    monkeypatch.setattr(patcher, "shell", _stub_module(fake_run))
    profile = Profile(repo="r", path=repo, branch="main")
    result = patch_repo(
        profile,
        dep_name="yaml",
        new_version="2.8.3",
        cve_id="CVE-1",
        ecosystem="npm",
    )
    assert result.status is PatchStatus.NOOP
    # NOOP must short-circuit BEFORE running npm install (no side effects on the lockfile).
    assert not any(c[:2] == ("npm", "install") for c in calls)


def test_patch_repo_npm_direct_install_moves_lockfile_to_done(tmp_path, monkeypatch):
    """A successful `npm install <pkg>@^<new>` that updates the lockfile yields DONE."""
    repo = _make_npm_repo(
        tmp_path,
        lockfile_contents={
            "lockfileVersion": 3,
            "packages": {"node_modules/yaml": {"version": "2.8.1"}},
        },
        package_json_contents={"name": "app"},
    )
    lockfile = repo / "package-lock.json"
    state = {"status_calls": 0}

    def fake_run(args, **_kw):
        key = tuple(args)
        if key == ("git", "--no-pager", "status", "--porcelain", "--untracked-files=no"):
            state["status_calls"] += 1
            # First call (preflight) clean; second call (post-install) dirty
            return CommandResult(0, "" if state["status_calls"] == 1 else " M package-lock.json\n", "")
        if key[:2] == ("npm", "install") and len(key) > 2:
            # Simulate npm bumping the lockfile.
            lockfile.write_text(
                json.dumps(
                    {
                        "lockfileVersion": 3,
                        "packages": {"node_modules/yaml": {"version": "2.8.3"}},
                    }
                ),
                encoding="utf-8",
            )
        return CommandResult(0, "", "")

    monkeypatch.setattr(patcher, "shell", _stub_module(fake_run))
    profile = Profile(repo="r", path=repo, branch="main")
    result = patch_repo(
        profile,
        dep_name="yaml",
        new_version="2.8.3",
        cve_id="CVE-2026-33532",
        ecosystem="npm",
    )
    assert result.status is PatchStatus.DONE
    assert result.note == "bumped to >=2.8.3"


def test_patch_repo_npm_falls_back_to_overrides_when_install_did_not_move(tmp_path, monkeypatch):
    """When `npm install <pkg>@^X` leaves the lockfile unchanged (typical transitive case),
    acidbase inserts an `overrides` entry and re-runs npm install.
    """
    repo = _make_npm_repo(
        tmp_path,
        lockfile_contents={
            "lockfileVersion": 3,
            "packages": {"node_modules/yaml": {"version": "2.8.1"}},
        },
        package_json_contents={"name": "app"},
    )
    lockfile = repo / "package-lock.json"
    npm_install_count = {"n": 0}
    state = {"status_calls": 0}

    def fake_run(args, **_kw):
        key = tuple(args)
        if key == ("git", "--no-pager", "status", "--porcelain", "--untracked-files=no"):
            state["status_calls"] += 1
            return CommandResult(0, "" if state["status_calls"] == 1 else " M package-lock.json\n", "")
        if key[:2] == ("npm", "install"):
            npm_install_count["n"] += 1
            # First call (with @^2.8.3 spec) does NOT move the lockfile — simulates transitive pin.
            # Second call (with overrides in place) updates it.
            if npm_install_count["n"] == 2:
                lockfile.write_text(
                    json.dumps(
                        {
                            "lockfileVersion": 3,
                            "packages": {"node_modules/yaml": {"version": "2.8.3"}},
                        }
                    ),
                    encoding="utf-8",
                )
        return CommandResult(0, "", "")

    monkeypatch.setattr(patcher, "shell", _stub_module(fake_run))
    profile = Profile(repo="r", path=repo, branch="main")
    result = patch_repo(
        profile,
        dep_name="yaml",
        new_version="2.8.3",
        cve_id="CVE-2026-33532",
        ecosystem="npm",
    )
    assert result.status is PatchStatus.DONE
    # Override was inserted into package.json on the fallback path.
    data = json.loads((repo / "package.json").read_text(encoding="utf-8"))
    assert data["overrides"] == {"yaml": "^2.8.3"}


# ---------------------------------------------------------------------------
# Secondary uv-export requirements files (e.g. producer/requirements.txt)
# ---------------------------------------------------------------------------


def test_read_uv_lock_dep_version_parses_and_handles_garbage(tmp_path):
    """`_read_uv_lock_dep_version` finds the package version and tolerates junk."""
    lock = tmp_path / "uv.lock"
    lock.write_text(_UV_LOCK.format(dep="authlib", ver="1.7.2"), encoding="utf-8")
    assert patcher._read_uv_lock_dep_version(lock, "authlib") == "1.7.2"
    assert patcher._read_uv_lock_dep_version(lock, "absent") is None
    bad = tmp_path / "bad.lock"
    bad.write_text("not [[ valid toml", encoding="utf-8")
    assert patcher._read_uv_lock_dep_version(bad, "authlib") is None


def test_parse_uv_export_header_accepts_valid_and_rejects_unsafe(tmp_path):
    """Only a verifiable `uv export ... -o <thisfile>` header yields a runnable argv."""
    f = tmp_path / "f.txt"
    f.write_text(_UV_EXPORT_HEADER + "authlib==1.6.5\n", encoding="utf-8")
    # Valid: command is `uv export` and -o target matches the file's rel path.
    assert patcher._parse_uv_export_header(f, "producer/requirements.txt") == [
        "uv",
        "export",
        "--no-hashes",
        "--no-dev",
        "-o",
        "producer/requirements.txt",
    ]
    # Safety guard: -o target does not match the file being regenerated.
    assert patcher._parse_uv_export_header(f, "other/requirements.txt") is None
    # Safety guard: header present but the command is not `uv export`.
    bad = tmp_path / "b.txt"
    bad.write_text("# autogenerated by uv\n#    rm -rf / -o producer/requirements.txt\n", encoding="utf-8")
    assert patcher._parse_uv_export_header(bad, "producer/requirements.txt") is None
    # No autogenerated header at all (hand-maintained file).
    plain = tmp_path / "p.txt"
    plain.write_text("authlib==1.6.5\n", encoding="utf-8")
    assert patcher._parse_uv_export_header(plain, "p.txt") is None


def _write_uv_repo(tmp_path: Path, *, dep: str, lock_ver: str) -> Path:
    """Creates a uv repo skeleton with uv.lock pinning ``dep`` at ``lock_ver``."""
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "uv.lock").write_text(_UV_LOCK.format(dep=dep, ver=lock_ver), encoding="utf-8")
    (repo / "pyproject.toml").write_text("[project]\nname='r'\nversion='0'\n", encoding="utf-8")
    return repo


def test_apply_uv_bump_regenerates_secondary_export_when_root_satisfied(tmp_path, monkeypatch):
    """The vlc/producer case: root already patched, a stale uv-export file is regenerated.
    `uv add` is skipped (root lock already satisfies the target), the secondary
    file's own recorded `uv export` command is re-run, and the regenerated file
    is committed. The note makes the secondary-only refresh explicit.
    """
    repo = _write_uv_repo(tmp_path, dep="authlib", lock_ver="1.7.2")
    (repo / "producer").mkdir()
    producer = repo / "producer" / "requirements.txt"
    producer.write_text(_UV_EXPORT_HEADER + "authlib==1.6.5\n", encoding="utf-8")
    calls: list[tuple[str, ...]] = []

    def fake_run(args, *, cwd=None, **_kw):
        key = tuple(args)
        calls.append(key)
        if key == ("git", "ls-files"):
            return CommandResult(0, "pyproject.toml\nuv.lock\nproducer/requirements.txt\n", "")
        if key[:2] == ("uv", "export") and any("producer/requirements.txt" in a for a in key):
            producer.write_text(_UV_EXPORT_HEADER + "authlib==1.7.2\n", encoding="utf-8")
            return CommandResult(0, "", "")
        if key == ("git", "--no-pager", "status", "--porcelain", "--untracked-files=no"):
            return CommandResult(0, " M producer/requirements.txt\n", "")
        return CommandResult(0, "", "")

    monkeypatch.setattr(patcher, "shell", _stub_module(fake_run))
    result = PatchResult(repo="vlc", path=repo, status=PatchStatus.WOULD_RUN)
    out = patcher._apply_uv_bump(result, path=repo, dep_name="authlib", new_version="1.6.9", cve_id="CVE-2026-27962")
    assert out.status is PatchStatus.DONE
    assert "root already >= 1.6.9" in out.note
    assert "regenerated producer/requirements.txt" in out.note
    # uv add must NOT have run: the root lock already satisfied the target.
    assert not any(c[:2] == ("uv", "add") for c in calls)
    # The secondary file now satisfies the threshold.
    assert "authlib==1.7.2" in producer.read_text(encoding="utf-8")
    # The regenerated secondary file is part of the commit.
    assert any(c[:2] == ("git", "add") and "producer/requirements.txt" in c for c in calls)


def test_apply_uv_bump_noop_when_root_satisfied_and_no_secondary(tmp_path, monkeypatch):
    """Root lock already satisfies and nothing else is stale => NOOP, no uv add."""
    repo = _write_uv_repo(tmp_path, dep="authlib", lock_ver="1.7.2")
    calls: list[tuple[str, ...]] = []

    def fake_run(args, *, cwd=None, **_kw):
        key = tuple(args)
        calls.append(key)
        if key == ("git", "ls-files"):
            return CommandResult(0, "pyproject.toml\nuv.lock\n", "")
        return CommandResult(0, "", "")  # status: clean

    monkeypatch.setattr(patcher, "shell", _stub_module(fake_run))
    result = PatchResult(repo="r", path=repo, status=PatchStatus.WOULD_RUN)
    out = patcher._apply_uv_bump(result, path=repo, dep_name="authlib", new_version="1.6.9", cve_id="CVE-1")
    assert out.status is PatchStatus.NOOP
    assert "already >= 1.6.9" in out.note
    assert not any(c[:2] == ("uv", "add") for c in calls)


def test_apply_uv_bump_uvaddfail_records_stderr_in_note(tmp_path, monkeypatch):
    """A failed `uv add` now surfaces its stderr tail in the Summary note (no -v needed)."""
    repo = _write_uv_repo(tmp_path, dep="authlib", lock_ver="1.6.5")  # below target -> uv add runs

    def fake_run(args, *, cwd=None, **_kw):
        if tuple(args)[:2] == ("uv", "add"):
            return CommandResult(2, "", "x No solution found: authlib pin conflict")
        return CommandResult(0, "", "")

    monkeypatch.setattr(patcher, "shell", _stub_module(fake_run))
    result = PatchResult(repo="r", path=repo, status=PatchStatus.WOULD_RUN)
    out = patcher._apply_uv_bump(result, path=repo, dep_name="authlib", new_version="1.6.9", cve_id="CVE-1")
    assert out.status is PatchStatus.UVADDFAIL
    assert "No solution found" in out.note


def test_apply_uv_bump_uvaddfail_note_keeps_resolver_tail(tmp_path, monkeypatch):
    """The transcriber case: warning noise at the head must not displace the resolver verdict.
    uv prints `warning: VIRTUAL_ENV ... does not match ...` first and the
    `Because ...` resolution chain last; a head-truncated note showed only the
    warning. The note must keep the tail.
    """
    repo = _write_uv_repo(tmp_path, dep="black", lock_ver="25.9.0")
    noise = "warning: `VIRTUAL_ENV=...` does not match the project environment path `.venv`\n" * 6
    verdict = (
        "x No solution found when resolving dependencies:\n"
        "Because there is no version of torch==2.12.0.dev20260407 we conclude unsatisfiable."
    )

    def fake_run(args, *, cwd=None, **_kw):
        if tuple(args)[:2] == ("uv", "add"):
            return CommandResult(1, "", noise + verdict)
        return CommandResult(0, "", "")

    monkeypatch.setattr(patcher, "shell", _stub_module(fake_run))
    result = PatchResult(repo="transcriber", path=repo, status=PatchStatus.WOULD_RUN)
    out = patcher._apply_uv_bump(result, path=repo, dep_name="black", new_version="26.3.1", cve_id="CVE-2026-32274")
    assert out.status is PatchStatus.UVADDFAIL
    assert "unsatisfiable" in out.note  # the tail survived
    assert "\u2026" in out.note  # head noise was truncated away


def test_apply_uv_bump_fails_when_lock_stays_below_target_after_uv_add(tmp_path, monkeypatch):
    """The ratemyhuman case: `uv add` exits 0 but an override caps the lock below target.
    `[tool.uv] override-dependencies` REPLACE the project's own requirement, so
    `uv add "pillow>=12.3.0"` succeeded while the locked pillow stayed at
    12.2.0 — the run then committed a specifier-only bump and later clean
    re-runs reported a false `NOOP already >= 12.3.0`. The post-add lock
    re-read must surface a real UVADDFAIL that points at overrides, and the
    uv add edits must be reverted so the repo stays clean and re-runnable.
    """
    repo = _write_uv_repo(tmp_path, dep="pillow", lock_ver="12.2.0")  # below target -> uv add runs
    calls: list[tuple[str, ...]] = []

    def fake_run(args, *, cwd=None, **_kw):
        key = tuple(args)
        calls.append(key)
        # uv add exits 0 WITHOUT moving the locked version (override in effect).
        return CommandResult(0, "", "")

    monkeypatch.setattr(patcher, "shell", _stub_module(fake_run))
    result = PatchResult(repo="ratemyhuman", path=repo, status=PatchStatus.WOULD_RUN)
    out = patcher._apply_uv_bump(result, path=repo, dep_name="Pillow", new_version="12.3.0", cve_id="CVE-2026-59200")
    assert out.status is PatchStatus.UVADDFAIL
    assert "still pins Pillow==12.2.0" in out.note
    assert "override-dependencies" in out.note
    assert ("uv", "add", "--no-sync", "Pillow>=12.3.0") in calls
    # The specifier-only edits are reverted, and no commit is ever attempted.
    assert ("git", "checkout", "--", "pyproject.toml", "uv.lock") in calls
    assert not any(c[:2] == ("git", "commit") for c in calls)
    assert not any(c[:2] == ("uv", "export") for c in calls)


def test_apply_uv_bump_passes_no_sync_so_target_venv_is_never_touched(tmp_path, monkeypatch):
    """The CanonFodder case: the bump must run `uv add --no-sync`, never a syncing add.
    A syncing `uv add` (re)creates the project venv, and a cross-platform uv
    (Windows uv reaching a WSL checkout whose UNC spelling escapes
    `shell.wsl_routing`, or WSL-side acidbase against an /mnt/c repo) treats
    the foreign-platform .venv as invalid and rebuilds it — on CanonFodder
    the rebuild over //wsl.localhost/ deleted lib/ and then died on the
    dangling lib64 symlink, leaving a gutted env. The flow only needs
    pyproject.toml + uv.lock to move, so uv must stay out of site-packages.
    """
    repo = _write_uv_repo(tmp_path, dep="cryptography", lock_ver="48.0.1")  # below target -> uv add runs
    calls: list[tuple[str, ...]] = []

    def fake_run(args, *, cwd=None, **_kw):
        key = tuple(args)
        calls.append(key)
        if key[:2] == ("uv", "add"):
            # Simulating a real uv add: the re-lock moves the resolved version.
            (repo / "uv.lock").write_text(_UV_LOCK.format(dep="cryptography", ver="50.0.0"), encoding="utf-8")
            return CommandResult(0, "", "")
        if key == ("git", "ls-files"):
            return CommandResult(0, "pyproject.toml\nuv.lock\n", "")
        if key == ("git", "--no-pager", "status", "--porcelain", "--untracked-files=no"):
            return CommandResult(0, " M pyproject.toml\n", "")
        return CommandResult(0, "", "")

    monkeypatch.setattr(patcher, "shell", _stub_module(fake_run))
    result = PatchResult(repo="CanonFodder", path=repo, status=PatchStatus.WOULD_RUN)
    out = patcher._apply_uv_bump(
        result, path=repo, dep_name="cryptography", new_version="50.0.0", cve_id="CVE-2026-69247"
    )
    assert out.status is PatchStatus.DONE
    assert ("uv", "add", "--no-sync", "cryptography>=50.0.0") in calls
    # No uv invocation in the whole flow may sync the environment.
    assert all("--no-sync" in c for c in calls if c[:2] == ("uv", "add"))
    assert not any(c[:2] == ("uv", "sync") for c in calls)


def test_venv_flavor_detects_layouts(tmp_path):
    """_venv_flavor classifies venvs by directory markers, not interpreter files.
    A Linux venv's bin/python symlink may not resolve across the 9P share,
    so only the bin/ vs Scripts/ directory shape is trusted.
    """
    assert patcher._venv_flavor(tmp_path / "missing" / ".venv") == "absent"
    win = tmp_path / "win" / ".venv"
    (win / "Scripts").mkdir(parents=True)
    assert patcher._venv_flavor(win) == "windows"
    posix = tmp_path / "posix" / ".venv"
    (posix / "bin").mkdir(parents=True)
    assert patcher._venv_flavor(posix) == "posix"
    both = tmp_path / "both" / ".venv"
    (both / "bin").mkdir(parents=True)
    (both / "Scripts").mkdir()
    assert patcher._venv_flavor(both) == "unknown"
    gutted = tmp_path / "gutted" / ".venv"
    gutted.mkdir(parents=True)
    (gutted / "pyvenv.cfg").write_text("home = /usr/bin\n", encoding="utf-8")
    assert patcher._venv_flavor(gutted) == "unknown"


def test_patch_repo_sync_env_runs_guarded_sync_after_done(tmp_path, monkeypatch):
    """--sync-env wiring: after the commit lands, `uv sync --frozen` runs and the note says so.
    An absent .venv is the deterministic cross-platform case: the executing
    side simply creates a fresh native env, so the sync always proceeds.
    """
    repo = _make_repo(tmp_path)
    state = {"status_calls": 0}
    calls: list[tuple[str, ...]] = []

    def fake_run(args, *, cwd=None, capture=True, check=False, env=None):
        key = tuple(args)
        calls.append(key)
        if key == ("git", "--no-pager", "status", "--porcelain", "--untracked-files=no"):
            state["status_calls"] += 1
            if state["status_calls"] == 1:
                return CommandResult(0, "", "")
            return CommandResult(0, "M pyproject.toml\n", "")
        return CommandResult(0, "", "")

    monkeypatch.setattr(patcher, "shell", _stub_module(fake_run))
    profile = Profile(repo="r", path=repo, branch="main")
    result = patch_repo(profile, dep_name="GitPython", new_version="3.1.50", cve_id="CVE-1", sync_env=True)
    assert result.status is PatchStatus.DONE
    assert ("uv", "sync", "--frozen") in calls
    # The sync happens only after the security commit succeeded.
    commit_idx = next(i for i, c in enumerate(calls) if c[:3] == ("git", "commit", "-m"))
    assert calls.index(("uv", "sync", "--frozen")) > commit_idx
    assert result.note.endswith("synced env")


def test_sync_environment_skips_foreign_platform_venv(tmp_path, monkeypatch):
    """A posix .venv reached by a Windows-side uv is reported, never rebuilt.
    This is the --sync-env twin of the CanonFodder guard: eager syncing must
    not reintroduce the cross-platform venv rebuild that --no-sync removed.
    """
    repo = _write_uv_repo(tmp_path, dep="cryptography", lock_ver="48.0.1")  # below target -> uv add runs
    (repo / ".venv" / "bin").mkdir(parents=True)
    calls: list[tuple[str, ...]] = []

    def fake_run(args, *, cwd=None, **_kw):
        key = tuple(args)
        calls.append(key)
        if key[:2] == ("uv", "add"):
            # Simulating a real uv add: the re-lock moves the resolved version.
            (repo / "uv.lock").write_text(_UV_LOCK.format(dep="cryptography", ver="50.0.0"), encoding="utf-8")
            return CommandResult(0, "", "")
        if key == ("git", "ls-files"):
            return CommandResult(0, "pyproject.toml\nuv.lock\n", "")
        if key == ("git", "--no-pager", "status", "--porcelain", "--untracked-files=no"):
            return CommandResult(0, " M pyproject.toml\n", "")
        return CommandResult(0, "", "")

    monkeypatch.setattr(patcher, "shell", _stub_module(fake_run))
    monkeypatch.setattr(patcher.sys, "platform", "win32")
    result = PatchResult(repo="CanonFodder", path=repo, status=PatchStatus.WOULD_RUN)
    out = patcher._apply_uv_bump(
        result, path=repo, dep_name="cryptography", new_version="50.0.0", cve_id="CVE-1", sync_env=True
    )
    assert out.status is PatchStatus.DONE
    assert not any(c[:2] == ("uv", "sync") for c in calls)
    assert "env sync skipped: posix venv vs windows uv" in out.note


def test_sync_environment_syncs_posix_venv_through_wsl_routing(tmp_path, monkeypatch):
    """A WSL-routed repo syncs: the distro-native POSIX uv matches the posix venv.
    shell.run reroutes WSL UNC paths through the distro, so even a Windows
    host performs this sync with Linux uv against the Linux venv.
    """
    repo = _write_uv_repo(tmp_path, dep="cryptography", lock_ver="48.0.1")  # below target -> uv add runs
    (repo / ".venv" / "bin").mkdir(parents=True)
    calls: list[tuple[str, ...]] = []

    def fake_run(args, *, cwd=None, **_kw):
        key = tuple(args)
        calls.append(key)
        if key[:2] == ("uv", "add"):
            (repo / "uv.lock").write_text(_UV_LOCK.format(dep="cryptography", ver="50.0.0"), encoding="utf-8")
            return CommandResult(0, "", "")
        if key == ("git", "ls-files"):
            return CommandResult(0, "pyproject.toml\nuv.lock\n", "")
        if key == ("git", "--no-pager", "status", "--porcelain", "--untracked-files=no"):
            return CommandResult(0, " M pyproject.toml\n", "")
        return CommandResult(0, "", "")

    stub = _stub_module(fake_run)
    stub.wsl_routing = staticmethod(lambda cwd: ("Ubuntu", "/home/user/repo"))
    monkeypatch.setattr(patcher, "shell", stub)
    monkeypatch.setattr(patcher.sys, "platform", "win32")
    result = PatchResult(repo="CanonFodder", path=repo, status=PatchStatus.WOULD_RUN)
    out = patcher._apply_uv_bump(
        result, path=repo, dep_name="cryptography", new_version="50.0.0", cve_id="CVE-1", sync_env=True
    )
    assert out.status is PatchStatus.DONE
    assert ("uv", "sync", "--frozen") in calls
    assert out.note.endswith("synced env")


def test_sync_environment_failure_keeps_done_and_reports_tail(tmp_path, monkeypatch):
    """A failing sync never demotes the row: the security commit already landed."""
    repo = _write_uv_repo(tmp_path, dep="cryptography", lock_ver="48.0.1")  # below target -> uv add runs
    calls: list[tuple[str, ...]] = []

    def fake_run(args, *, cwd=None, **_kw):
        key = tuple(args)
        calls.append(key)
        if key[:2] == ("uv", "add"):
            (repo / "uv.lock").write_text(_UV_LOCK.format(dep="cryptography", ver="50.0.0"), encoding="utf-8")
            return CommandResult(0, "", "")
        if key[:2] == ("uv", "sync"):
            return CommandResult(1, "", "error: distribution not found for torch")
        if key == ("git", "ls-files"):
            return CommandResult(0, "pyproject.toml\nuv.lock\n", "")
        if key == ("git", "--no-pager", "status", "--porcelain", "--untracked-files=no"):
            return CommandResult(0, " M pyproject.toml\n", "")
        return CommandResult(0, "", "")

    monkeypatch.setattr(patcher, "shell", _stub_module(fake_run))
    result = PatchResult(repo="r", path=repo, status=PatchStatus.WOULD_RUN)
    out = patcher._apply_uv_bump(
        result, path=repo, dep_name="cryptography", new_version="50.0.0", cve_id="CVE-1", sync_env=True
    )
    assert out.status is PatchStatus.DONE
    assert "env sync failed" in out.note
    assert "distribution not found" in out.note


def test_apply_uv_bump_reports_manual_for_hand_maintained_secondary(tmp_path, monkeypatch):
    """A non-uv-export secondary file pinning the dep low is reported, never auto-edited."""
    repo = _write_uv_repo(tmp_path, dep="authlib", lock_ver="1.7.2")  # root satisfied
    (repo / "svc").mkdir()
    hand = repo / "svc" / "requirements.txt"
    hand.write_text("# hand maintained\nauthlib==1.6.5\n", encoding="utf-8")
    calls: list[tuple[str, ...]] = []

    def fake_run(args, *, cwd=None, **_kw):
        key = tuple(args)
        calls.append(key)
        if key == ("git", "ls-files"):
            return CommandResult(0, "pyproject.toml\nuv.lock\nsvc/requirements.txt\n", "")
        return CommandResult(0, "", "")  # status: clean (we changed nothing)

    monkeypatch.setattr(patcher, "shell", _stub_module(fake_run))
    result = PatchResult(repo="r", path=repo, status=PatchStatus.WOULD_RUN)
    out = patcher._apply_uv_bump(result, path=repo, dep_name="authlib", new_version="1.6.9", cve_id="CVE-1")
    assert out.status is PatchStatus.NOOP
    assert "manual attention" in out.note
    assert "svc/requirements.txt" in out.note
    # We never tried to (re-)export a hand-maintained file.
    assert not any(c[:2] == ("uv", "export") for c in calls)


# ---------------------------------------------------------------------------
# Root requirements.txt guard + hook-aware commit retry (url-rag regression)
# ---------------------------------------------------------------------------


def test_apply_uv_bump_leaves_non_export_root_requirements_alone(tmp_path, monkeypatch):
    """The url-rag case: a curated root requirements.txt is neither exported nor staged.
    url-rag's root file is generated by scripts/sync_requirements.py (direct
    deps only, Airflow core filtered for the Astro Runtime ONBUILD guard);
    acidbase used to clobber it with a full transitive `uv export`.
    """
    repo = _write_uv_repo(tmp_path, dep="pyjwt", lock_ver="2.11.0")  # below target -> uv add runs
    (repo / "requirements.txt").write_text(
        "# autogenerated by scripts/sync_requirements.py from pyproject.toml\npyjwt\n",
        encoding="utf-8",
    )
    calls: list[tuple[str, ...]] = []

    def fake_run(args, *, cwd=None, **_kw):
        key = tuple(args)
        calls.append(key)
        if key == ("git", "ls-files"):
            return CommandResult(0, "pyproject.toml\nrequirements.txt\nuv.lock\n", "")
        if key[:2] == ("uv", "add"):
            # Simulating a real uv add: the re-lock moves the resolved version.
            (repo / "uv.lock").write_text(_UV_LOCK.format(dep="pyjwt", ver="2.12.0"), encoding="utf-8")
            return CommandResult(0, "", "")
        if key == ("git", "--no-pager", "status", "--porcelain", "--untracked-files=no"):
            return CommandResult(0, " M pyproject.toml\n", "")  # uv add changed the project files
        return CommandResult(0, "", "")

    monkeypatch.setattr(patcher, "shell", _stub_module(fake_run))
    result = PatchResult(repo="url-rag", path=repo, status=PatchStatus.WOULD_RUN)
    out = patcher._apply_uv_bump(result, path=repo, dep_name="PyJWT", new_version="2.12.0", cve_id="CVE-2026-32597")
    assert out.status is PatchStatus.DONE
    # The curated file is never exported over and never staged.
    assert not any(c[:2] == ("uv", "export") for c in calls)
    assert ("git", "add", "pyproject.toml", "uv.lock") in calls
    # It is also not flagged manual: it does not pin the dep with `==` at all.
    assert "manual" not in out.note


def test_apply_uv_bump_flags_pinned_non_export_root_as_manual(tmp_path, monkeypatch):
    """A curated root file that DOES pin the dep too low is reported for manual attention."""
    repo = _write_uv_repo(tmp_path, dep="pyjwt", lock_ver="2.12.0")  # root satisfied -> no uv add
    (repo / "requirements.txt").write_text("# hand maintained\npyjwt==2.11.0\n", encoding="utf-8")
    calls: list[tuple[str, ...]] = []

    def fake_run(args, *, cwd=None, **_kw):
        key = tuple(args)
        calls.append(key)
        if key == ("git", "ls-files"):
            return CommandResult(0, "pyproject.toml\nrequirements.txt\nuv.lock\n", "")
        return CommandResult(0, "", "")  # status: clean (nothing changed on disk)

    monkeypatch.setattr(patcher, "shell", _stub_module(fake_run))
    result = PatchResult(repo="r", path=repo, status=PatchStatus.WOULD_RUN)
    out = patcher._apply_uv_bump(result, path=repo, dep_name="PyJWT", new_version="2.12.0", cve_id="CVE-1")
    assert out.status is PatchStatus.NOOP
    assert "manual attention" in out.note
    assert "requirements.txt" in out.note
    assert not any(c[:2] == ("uv", "export") for c in calls)


def test_apply_uv_bump_regenerates_uv_export_root(tmp_path, monkeypatch):
    """A root requirements.txt that IS a uv-export artifact is regenerated via its recorded command."""
    repo = _write_uv_repo(tmp_path, dep="pyjwt", lock_ver="2.12.0")  # root satisfied -> no uv add
    root = repo / "requirements.txt"
    root.write_text(_ROOT_EXPORT_HEADER + "pyjwt==2.11.0\n", encoding="utf-8")
    calls: list[tuple[str, ...]] = []

    def fake_run(args, *, cwd=None, **_kw):
        key = tuple(args)
        calls.append(key)
        if key == ("git", "ls-files"):
            return CommandResult(0, "pyproject.toml\nrequirements.txt\nuv.lock\n", "")
        if key[:2] == ("uv", "export"):
            root.write_text(_ROOT_EXPORT_HEADER + "pyjwt==2.12.0\n", encoding="utf-8")
            return CommandResult(0, "", "")
        if key == ("git", "--no-pager", "status", "--porcelain", "--untracked-files=no"):
            return CommandResult(0, " M requirements.txt\n", "")
        return CommandResult(0, "", "")

    monkeypatch.setattr(patcher, "shell", _stub_module(fake_run))
    result = PatchResult(repo="r", path=repo, status=PatchStatus.WOULD_RUN)
    out = patcher._apply_uv_bump(result, path=repo, dep_name="PyJWT", new_version="2.12.0", cve_id="CVE-1")
    assert out.status is PatchStatus.DONE
    assert "regenerated requirements.txt" in out.note
    # The file's own recorded command was re-run verbatim.
    assert ("uv", "export", "--frozen", "--output-file=requirements.txt") in calls
    # The regenerated root file is part of the commit.
    assert ("git", "add", "pyproject.toml", "uv.lock", "requirements.txt") in calls


def test_commit_files_retries_once_when_hooks_modify_files(tmp_path, monkeypatch):
    """A commit aborted by file-modifying pre-commit hooks is re-staged and retried once."""
    repo = _write_uv_repo(tmp_path, dep="pyjwt", lock_ver="2.12.0")
    commits = {"n": 0}
    calls: list[tuple[str, ...]] = []

    def fake_run(args, *, cwd=None, **_kw):
        key = tuple(args)
        calls.append(key)
        if key[:3] == ("git", "commit", "-m"):
            commits["n"] += 1
            if commits["n"] == 1:
                return CommandResult(1, "sync requirements...Failed\n- files were modified by this hook\n", "")
            return CommandResult(0, "", "")
        if key == ("git", "diff", "--quiet"):
            return CommandResult(1, "", "")  # worktree differs from index => hook edits
        return CommandResult(0, "", "")

    monkeypatch.setattr(patcher, "shell", _stub_module(fake_run))
    result = PatchResult(repo="r", path=repo, status=PatchStatus.WOULD_RUN)
    out = patcher._commit_files(
        result, path=repo, files=["pyproject.toml", "uv.lock"], dep_name="PyJWT", new_version="2.12.0", cve_id="CVE-1"
    )
    assert out.status is PatchStatus.DONE
    assert "re-staged pre-commit hook edits" in out.note
    assert commits["n"] == 2
    assert ("git", "add", "-u") in calls


def test_commit_files_no_retry_without_hook_edits(tmp_path, monkeypatch):
    """A commit failure with no unstaged edits (e.g. gitleaks finding) fails immediately."""
    repo = _write_uv_repo(tmp_path, dep="pyjwt", lock_ver="2.12.0")
    commits = {"n": 0}
    calls: list[tuple[str, ...]] = []

    def fake_run(args, *, cwd=None, **_kw):
        key = tuple(args)
        calls.append(key)
        if key[:3] == ("git", "commit", "-m"):
            commits["n"] += 1
            return CommandResult(1, "", "gitleaks detected secrets in staged files")
        if key == ("git", "diff", "--quiet"):
            return CommandResult(0, "", "")  # no hook edits
        return CommandResult(0, "", "")

    monkeypatch.setattr(patcher, "shell", _stub_module(fake_run))
    result = PatchResult(repo="r", path=repo, status=PatchStatus.WOULD_RUN)
    out = patcher._commit_files(
        result, path=repo, files=["pyproject.toml", "uv.lock"], dep_name="PyJWT", new_version="2.12.0", cve_id="CVE-1"
    )
    assert out.status is PatchStatus.COMMITFAIL
    assert commits["n"] == 1
    assert ("git", "add", "-u") not in calls
    assert "gitleaks detected secrets" in out.note


def test_commit_files_note_keeps_output_tail_when_retry_fails(tmp_path, monkeypatch):
    """COMMITFAIL notes keep the END of the hook output, where pre-commit prints verdicts."""
    repo = _write_uv_repo(tmp_path, dep="pyjwt", lock_ver="2.12.0")
    noise = "uv-lock....Passed\nruff...Skipped\n" * 30
    verdict = "sync requirements...Failed\n- files were modified by this hook"

    def fake_run(args, *, cwd=None, **_kw):
        key = tuple(args)
        if key[:3] == ("git", "commit", "-m"):
            return CommandResult(1, noise + verdict, "")
        if key == ("git", "diff", "--quiet"):
            return CommandResult(1, "", "")
        return CommandResult(0, "", "")

    monkeypatch.setattr(patcher, "shell", _stub_module(fake_run))
    result = PatchResult(repo="r", path=repo, status=PatchStatus.WOULD_RUN)
    out = patcher._commit_files(
        result, path=repo, files=["pyproject.toml", "uv.lock"], dep_name="PyJWT", new_version="2.12.0", cve_id="CVE-1"
    )
    assert out.status is PatchStatus.COMMITFAIL
    assert out.note.startswith("git commit failed:")
    assert "files were modified by this hook" in out.note  # the tail survived
    assert "\u2026" in out.note  # truncation marker present, head dropped


def test_output_tail_joins_strips_and_truncates():
    """_output_tail joins stdout+stderr, passes short text through, keeps long tails."""
    assert patcher._output_tail("short", "") == "short"
    assert patcher._output_tail("a\n", "b\n") == "a\nb"
    long_text = "x" * 400 + "VERDICT"
    tail = patcher._output_tail(long_text, limit=50)
    assert tail.endswith("VERDICT")
    assert tail.startswith("\u2026")
    assert len(tail) == 51
